### ISSUE TITLE
support native call

### ISSUE THREAD

**Issue by netpyoung** [Microsoft/schemy#10]
Do you have a plan to support interop .net?

https://clojure.org/reference/java_interop

like

```scheme
(Console/WriteLine "A")
(.ToString 1)
```

**Comment by kflu** [comment]
We do support [interop with .NET](https://github.com/Microsoft/schemy#extending-schemy-in-net) today, but not in the form you mentioned. 

Specifically, Schemy don't support accessing .NET functions unless they are **explicitly exposed (registered)** via the interpreter. Schemy is used as a embedding language for users to extend the application business logic. In most cases, it is a major security concern letting Schemy script accessing anything the host platform (application) can access, e.g., file system, etc. 

Languages like Clojure, IronPython, etc, have a different goal - they are full-fledged language built on that runtime (JRE/CLR), while they can, they are not intended to be used as embedded languages. In fact, if used as embedded languages, you've to put a lot of effort on how to sandbox them.
