### ISSUE TITLE
alternative GetInitializeFiles for reading `init.ss`

### ISSUE THREAD

**Issue by netpyoung** [Microsoft/schemy#7]
I tested `schemy` on Unity3D gameengine.
but when i try, using dll direcly, I got error on `GetInitializeFiles`

https://github.com/Microsoft/schemy/blob/master/src/schemy/Schemy.cs#L54

Because, On Unity, fail to get resource from dll, 
```csharp
var names = Assembly.GetExecutingAssembly().GetManifestResourceNames();
names.Count == 0
```

how about make some mechanism alternative `GetInitializeFiles` ?

**Comment by kflu** [comment]
Hi thanks for reporting. Could you post the detail error message and exception? I want to know why in Unity it fails to load resource files. 

The reason I go with resource files is because it's embedded into the assembly and thus easier to use and deploy. 

As you said, I think it's good to provide an alternative to load `init.ss`. But I just want to understand the whole picture before going deeper.

**Comment by netpyoung** [comment]
I got follow error on Interpreter constructor.

```cs
NullReferenceException: Object reference not set to an instance of an object
Schemy.Interpreter+<GetInitializeFiles>d__5.MoveNext () (at <f7e0787f1e18405798aa9ba277be8de6>:0)
Schemy.Interpreter..ctor (System.Collections.Generic.IEnumerable`1[T] environmentInitializers, Schemy.IFileSystemAccessor fsAccessor) (at <f7e0787f1e18405798aa9ba277be8de6>:0)
main.Start () (at Assets/main.cs:24)
```

here is code what i used

```cs
        void Start ()
	{
		string inputString = "(define A 10)";
		var names = Assembly.GetExecutingAssembly().GetManifestResourceNames() ;
		foreach (string s in names)
		{
			Debug.Log(s);
		}
		Debug.Log(names.Length);

names.Length -> 0
24 line->	Interpreter interpreter = new Interpreter();   
		using (TextReader tr = new StringReader(inputString))
		{
			Interpreter.EvaluationResult result = interpreter.Evaluate(tr);
			if (result.Error != null)
			{
				Debug.LogError(result.Error);
				return;
			}
			Debug.Log(result.Result);
		}
		
		using (TextReader tr = new StringReader("A"))
		{
			Interpreter.EvaluationResult result = interpreter.Evaluate(tr);
			if (result.Error != null)
			{
				Debug.LogError(result.Error);
				return;
			}
			Debug.Log(result.Result);
		}
	}
```

**Comment by kflu** [comment]
This is strange. But if you try changing

    using (Stream stream = Assembly.GetExecutingAssembly().GetManifestResourceStream("init.ss"))

to 

    using (Stream stream = typeof(Interpreter).Assembly.GetManifestResourceStream("init.ss"))

I wonder if that solves the problem. Is it possible for you to try and confirm that?


```
diff --git a/src/schemy/Schemy.cs b/src/schemy/Schemy.cs
index 668752e..c583849 100644
--- a/src/schemy/Schemy.cs
+++ b/src/schemy/Schemy.cs
@@ -51,7 +51,7 @@ namespace Schemy
 
         private IEnumerable<TextReader> GetInitializeFiles()
         {
-            using (Stream stream = Assembly.GetExecutingAssembly().GetManifestResourceStream("init.ss"))
+            using (Stream stream = typeof(Interpreter).Assembly.GetManifestResourceStream("init.ss"))
             using (StreamReader reader = new StreamReader(stream))
             {
                 yield return reader;
```

**Comment by kflu** [comment]
Yeah I see. So the Unity engine loads your DLL in a special way that the entry assembly is `null`. I can change that to the `Interpreter` assembly as well. But then the contract of where to load `.init.ss` changes - just a little bit - from loading it from the application directory to the directory where the `Interpreter` assembly resides. I think this is OK as in most of the cases they are the same, plus it works for this special scenario. 

I'll push a change to this.
